---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gridScale
rules:
  - apiGroups: ["*"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "update"]



---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gridScale
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gridScale
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gridScale
subjects:
  - kind: ServiceAccount
    name: gridScale
    namespace: kube-system


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gridScale
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gridScale
  template:
    metadata:
      labels:
        app: gridScale
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      serviceAccountName: gridScale
      
      containers:
        - name: gridScale
          image: kalaspuffar/gridScale
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 1000m
              memory: 3750Mi
            limits:
              cpu: 1750m
              memory: 7500mi


          env:
            - name: INTERVAL
              value: "15"
            - name: RABBIT_HOST
              value: "http://ec2-18-193-6-223.eu-central-1.compute.amazonaws.com/"
            - name: RABBIT_USER
              value: "worker"
            - name: RABBIT_PASS
              value: "king"
            - name: AUTOSCALING
              value: >
                1|5|2|default|FinalPro|test;
            - name: LOGS
              value: HIGH
           
